import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link'; // Ensure Link is available if needed, though Navigation uses it
import Navigation from "./components/Navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-cyan-400 overflow-hidden`}
      >
        <div className="flex h-screen w-screen overflow-hidden">
            {/* Sidebar */}
            <aside className="w-20 md:w-64 flex-shrink-0 z-20">
              <Navigation />
            </aside>
            {/* Main Content Area */}
            <main className="flex-1 h-full overflow-hidden relative flex flex-col">
                {children}
                
               {/* Global Background Ambience */}
               <div className="absolute inset-0 pointer-events-none z-[-1] bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-cyan-900/10 via-slate-950 to-slate-950" />
               <div className="absolute inset-0 pointer-events-none z-[-1] opacity-20 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] filter contrast-100 brightness-100" />
            </main>
        </div>
      </body>
    </html>
  );
}
