import os
import re
import json
import logging
import asyncio
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime
import redis.asyncio as redis
from dotenv import load_dotenv

logging.basicConfig(level=logging.INFO, format='%(asctime)s - [ArXivCrawler] - %(message)s')
logger = logging.getLogger("ArXivCrawler")

AILCC_ROOT = Path(__file__).resolve().parent.parent.parent
HIPPOCAMPUS = AILCC_ROOT / "hippocampus_storage"
NOTES_DIR = HIPPOCAMPUS / "scholar_notes"
PDF_DIR = HIPPOCAMPUS / "scholar_pdfs"
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")

# ArXiv API Constraints
ARXIV_API = "http://export.arxiv.org/api/query?id_list={}"

class ArXivRecursiveDaemon:
    def __init__(self):
        self.redis = None
        self.seen_crawls = set()
        PDF_DIR.mkdir(parents=True, exist_ok=True)

    async def connect(self):
        self.redis = redis.from_url(REDIS_URL, decode_responses=True)
        await self.redis.ping()
        logger.info("⚡ Connected to Redis Neural Synapse.")
        
        # Load state
        raw_state = await self.redis.smembers("ailcc:research:crawled_files")
        if raw_state:
            self.seen_crawls.update(raw_state)

    def extract_arxiv_ids(self, text: str) -> list:
        """Physical Regex compilation extracting pure mathematical arXiv IDs."""
        # Matches formats like: arXiv:2301.12345 or just 2301.12345v2
        patterns = [
            r"arxiv:[\\s]*([0-9]{4}\\.[0-9]{4,5}(?:v[0-9])?)",
            r"abs/([0-9]{4}\\.[0-9]{4,5}(?:v[0-9])?)"
        ]
        results = set()
        for pattern in patterns:
            found = re.findall(pattern, text, re.IGNORECASE)
            for f in found:
                results.add(f.strip())
        return list(results)

    async def fetch_arxiv_metadata(self, arxiv_id: str) -> dict:
        """Hits the mathematical arXiv XML Endpoint and extracts metadata."""
        url = ARXIV_API.format(arxiv_id)
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'AILCC_Swarm/1.0'})
            response = await asyncio.to_thread(urllib.request.urlopen, req, timeout=10)
            xml_data = response.read().decode('utf-8')
            
            # Barebones XML parsing without heavy external libs
            title_match = re.search(r'<title>([\\s\\S]*?)</title>', xml_data)
            summary_match = re.search(r'<summary>([\\s\\S]*?)</summary>', xml_data)
            
            # Strip XML tags from matches
            title = re.sub(r'<[^>]+>', '', title_match.group(1)).strip().replace('\\n', ' ') if title_match else f"ArXiv {arxiv_id}"
            summary = re.sub(r'<[^>]+>', '', summary_match.group(1)).strip().replace('\\n', ' ') if summary_match else ""
            
            return {"id": arxiv_id, "title": title, "abstract": summary}
        except Exception as e:
            logger.error(f"Failed to fetch ArXiv ID {arxiv_id}: {e}")
            return None

    async def generate_scholar_node(self, paper: dict):
        """Generates a LOCAL_ONLY markdown node for the newly discovered citation."""
        safe_title = "".join([c if c.isalnum() else "_" for c in paper['title']])[:50]
        md_filename = f"arxiv_{paper['id'].replace('.','_')}_{safe_title}.md"
        md_path = NOTES_DIR / md_filename
        
        if md_path.exists():
            return # Prevent overwriting existing nodes
            
        content = f"""---
title: "{paper['title']}"
zotero_key: "arxiv_{paper['id']}"
data_classification: LOCAL_ONLY
daemon: arxiv_recursive_daemon
depth: 1
tags: ["auto-crawler", "neuroscience"]
---

# {paper['title']}

**Abstract:**
{paper['abstract']}
"""
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        logger.info(f"✅ Recursion Level 1 Achieved: Spawning Node -> {md_filename}")
        
        # Broadcast discovery to War Room
        payload = {
            "signal_id": f"arxiv-{paper['id']}",
            "type": "NEW_ACADEMIC_ASSET",
            "message": f"Crawled Citation: {paper['title'][:60]}...",
            "timestamp": datetime.now().isoformat()
        }
        await self.redis.publish("NEURAL_SYNAPSE", json.dumps(payload))

    async def sweep_zotero_notes(self):
        logger.info("🔍 Initiating Level 1 Deep-Crawling sweep across Scholar Notes...")
        if not NOTES_DIR.exists():
            return
            
        # Only sweep Markdown files that haven't been crawled yet
        md_files = list(NOTES_DIR.glob("*.md"))
        for md_path in md_files:
            if md_path.name in self.seen_crawls:
                continue
                
            # Depth 1 Constraint: Do not crawl files that were generated by this daemon
            with open(md_path, 'r', encoding='utf-8') as f:
                text = f.read()
                if "depth: 1" in text or "daemon: arxiv_recursive_daemon" in text:
                    self.seen_crawls.add(md_path.name)
                    continue
                    
            logger.info(f"Scanning seed node: {md_path.name}")
            arxiv_ids = self.extract_arxiv_ids(text)
            
            for arxiv_id in arxiv_ids:
                if not await self.redis.sismember("ailcc:research:arxiv_cache", arxiv_id):
                    logger.info(f"🎯 Discovered unmapped ArXiv Citation: {arxiv_id}")
                    paper_meta = await self.fetch_arxiv_metadata(arxiv_id)
                    if paper_meta:
                        await self.generate_scholar_node(paper_meta)
                        await self.redis.sadd("ailcc:research:arxiv_cache", arxiv_id)
            
            # Mark file as completely crawled
            self.seen_crawls.add(md_path.name)
            await self.redis.sadd("ailcc:research:crawled_files", md_path.name)
            
    async def run(self):
        await self.connect()
        while True:
            await self.sweep_zotero_notes()
            # Enforce 12-hour biological pacing so the Mastermind DB isn't flooded instantly
            await asyncio.sleep(43200)

if __name__ == "__main__":
    load_dotenv(os.path.expanduser("~/.ailcc/credentials.env"))
    daemon = ArXivRecursiveDaemon()
    asyncio.run(daemon.run())
