#!/usr/bin/env python3
"""
bio_telemetry_daemon.py — Autonomous Apple Health Injection
=============================================================================
This daemon sweeps the designated iCloud Drive ingest folder for `health_export.json` 
files generated by the iOS "Apple Health Export Shortcut".

It processes biometric markers (Sleep Hours, resting HR, HRV) to calculate a 
unified Readiness Score (0-100) and publishes it via Redis.

Usage:
    python3 bio_telemetry_daemon.py --sweep
"""

import os
import json
import logging
import argparse
import asyncio
import redis
from pathlib import Path
from datetime import datetime
import shutil

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [Bio-Telemetry] %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger(__name__)

# ─── Config ───────────────────────────────────────────────────────────────────
# Expand user home directory securely
USER_HOME = Path.home()
ICLOUD_INGEST_DIR = USER_HOME / "Library/Mobile Documents/com~apple~CloudDocs/Shortcuts/AILCC_Bio_Ingest"
HIPPOCAMPUS_DIR = Path("/Users/infinite27/AILCC_PRIME/01_Areas/Codebases/ailcc/hippocampus_storage")
BIO_STATE_JSON = HIPPOCAMPUS_DIR / "bio_state.json"

REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
redis_client = redis.Redis(host=REDIS_HOST, port=6379, db=0, decode_responses=True)

def calculate_readiness(sleep_hours: float, hrv: float, rhr: float) -> int:
    """
    Calculates a proprietary 0-100 Readiness Score based on the provided metrics.
    Currently uses static thresholds, can be upgraded to rolling baselines.
    """
    score = 100

    # Sleep Penalty (Target: 8h)
    if sleep_hours < 7.5:
        score -= min(30, (7.5 - sleep_hours) * 10)
    
    # RHR Penalty (Target: < 60)
    if rhr > 60:
        score -= min(20, (rhr - 60) * 1.5)

    # HRV Bonus (Target: > 50)
    if hrv > 50:
        score += min(15, (hrv - 50) * 0.5)
    elif hrv < 40:
        score -= min(20, (40 - hrv) * 1.5)

    return int(max(0, min(100, score)))

def process_health_export(file_path: Path):
    try:
        data = json.loads(file_path.read_text())
        logger.info(f"Loaded raw export: {data}")

        sleep = float(data.get("sleep_hours", 0))
        hrv = float(data.get("hrv_ms", 0))
        rhr = float(data.get("rhr_bpm", 0))

        readiness = calculate_readiness(sleep, hrv, rhr)
        logger.info(f"Calculated Readiness Score: {readiness}% (Sleep: {sleep}h, HRV: {hrv}ms)")

        state_payload = {
            "last_updated": datetime.now().isoformat(),
            "metrics": {
                "sleep_hours": sleep,
                "hrv_ms": hrv,
                "rhr_bpm": rhr,
                "readiness_score": readiness
            },
            "source": "Apple_Health"
        }

        # Write to persistent Hippocampus JSON for the Conductor to read
        BIO_STATE_JSON.write_text(json.dumps(state_payload, indent=2))
        logger.info(f"Wrote biological state to {BIO_STATE_JSON.name}")

        # Broadcast signal to Nexus Dashboard via Redis
        signal = {
            "id": f"bio_{datetime.now().timestamp()}",
            "timestamp": datetime.now().isoformat(),
            "level": "info",
            "source": "Bio-Telemetry",
            "type": "BIOLOGICAL_STATE",
            "message": f"New Readiness Score: {readiness}%",
            "metadata": state_payload["metrics"]
        }
        redis_client.publish('neural_synapse', json.dumps(signal))

        # Backup & cleanup original file
        backup_dir = ICLOUD_INGEST_DIR / "processed_archive"
        os.makedirs(backup_dir, exist_ok=True)
        backup_path = backup_dir / f"health_export_{int(datetime.now().timestamp())}.json"
        
        # Move instead of delete for debugging history
        shutil.move(str(file_path), str(backup_path))
        logger.info(f"Export archived to {backup_path.name}")

    except Exception as e:
        logger.error(f"Failed to process health export: {e}")

def sweep_directory():
    logger.info(f"Sweeping ingest directory: {ICLOUD_INGEST_DIR}")
    
    if not ICLOUD_INGEST_DIR.exists():
        logger.warning("iCloud Drive ingest directory does not exist. (Has the iOS Shortcut run yet?)")
        # For development ease, we'll create the folder so the user can easily find it on their Mac
        os.makedirs(ICLOUD_INGEST_DIR, exist_ok=True)
        return

    export_file = ICLOUD_INGEST_DIR / "health_export.json"
    if export_file.exists():
        logger.info("Found pending health export! Processing...")
        process_health_export(export_file)
    else:
        logger.info("No pending exports found.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Bio Telemetry Daemon")
    parser.add_argument("--sweep", action="store_true", help="Sweep iCloud directory for Apple Health JSONs.")
    args = parser.parse_args()

    if args.sweep:
        sweep_directory()
    else:
        print("Run with --sweep flag to execute the daemon.")
