import os
import re
from pathlib import Path

NOTES_DIR = Path(__file__).parent.parent.parent / "hippocampus_storage" / "scholar_notes"

def infer_category(filename: str) -> str:
    filename_lower = filename.lower()
    
    # Check for Class or Week
    match = re.search(r'(class|week)[\s_]*(\d+)', filename_lower)
    if match:
        return f"{match.group(1).capitalize()} {match.group(2)}"
        
    # Check for Chapters
    match = re.search(r'chapter[\s_]*(\d+)', filename_lower)
    if match:
        return f"Chapter {match.group(1)}"
        
    if "assignment" in filename_lower:
        return "Assignments"
    if "syllabus" in filename_lower:
        return "Syllabus & Core Materials"
        
    return "Uncategorized Readings"

def generate_index():
    if not NOTES_DIR.exists():
        return
        
    courses = {}
    
    for md_file in NOTES_DIR.glob("MOODLE_*.md"):
        course_name = "Unknown Course"
        with open(md_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            for line in lines:
                if line.startswith("course:"):
                    course_name = line.split("course:")[1].strip().strip('"')
                    break
        
        category = infer_category(md_file.name)
        courses.setdefault(course_name, {}).setdefault(category, []).append(md_file.name)
        
    for course, categories in courses.items():
        safe_course = course.replace(" ", "_").replace("/", "-").replace("(", "").replace(")", "")
        index_path = NOTES_DIR / f"course_index_{safe_course}.md"
        
        # Sort categories nicely
        def cat_sort_key(k):
            if "Syllabus" in k: return (0, k)
            if "Class" in k or "Week" in k:
                nums = re.findall(r'\d+', k)
                return (1, int(nums[0]) if nums else 0)
            if "Chapter" in k:
                nums = re.findall(r'\d+', k)
                return (2, int(nums[0]) if nums else 0)
            if "Assignment" in k: return (3, k)
            return (4, k)
            
        sorted_categories = sorted(categories.keys(), key=cat_sort_key)
        
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(f"# Moodle Course Index: {course}\n\n")
            f.write("> **Auto-Generated by Vanguard Agent (`course_indexer.py`)**\n")
            f.write("> Telemetry aggregation of all local Moodle `.md` nodes mapped in the Hippocampus array.\n\n")
            
            for category in sorted_categories:
                f.write(f"## {category}\n")
                files = categories[category]
                files.sort()
                for file in files:
                    clean_name = file.replace(".md", "").replace("MOODLE_", "")
                    f.write(f"- [{clean_name}](./{file})\n")
                f.write("\n")
                
        print(f"✅ Generated semantic index artifact: {index_path.name}")

if __name__ == "__main__":
    generate_index()
