#!/usr/bin/env python3
"""
home_assistant_bridge.py — Physical Environment Sync (Sovereign Module)
=======================================================================
Reads the active Mastermind OS schedule generated by `the_conductor_daemon.py`
and fires webhooks to a local Home Assistant instance to synchronize the 
biological/physical environment (lights, temperature, blocking) with the 
current cognitive demand of the active task.

Usage:
    python3 home_assistant_bridge.py --sync
    python3 home_assistant_bridge.py --dry-run
"""

import os
import json
import logging
import argparse
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="%(asctime)s [HomeAssistant] %(message)s")
logger = logging.getLogger(__name__)

HIPPOCAMPUS_DIR = Path("/Users/infinite27/AILCC_PRIME/01_Areas/Codebases/ailcc/hippocampus_storage")
ROUTINE_JSON    = HIPPOCAMPUS_DIR / "calendar_matrix" / "daily_routine.json"

# Example local Home Assistant endpoint
HA_URL = os.environ.get("HA_WEBHOOK_URL", "http://homeassistant.local:8123/api/webhook/")

def get_active_task():
    """Reads the Conductor's daily routine and finds the currently active task."""
    if not ROUTINE_JSON.exists():
        logger.warning(f"No routine found at {ROUTINE_JSON}")
        return None

    try:
        data = json.loads(ROUTINE_JSON.read_text())
        now = datetime.now()

        for item in data.get("schedule", []):
            start = datetime.fromisoformat(item["start"])
            end = datetime.fromisoformat(item["end"])
            
            if start <= now <= end:
                return item
        return None
    except Exception as e:
        logger.error(f"Error parsing routine: {e}")
        return None

def trigger_ha_scene(domain: str, urgency: str, title: str, dry_run: bool = False):
    """Fires a webhook to Home Assistant to change the physical environment."""
    
    # Map Vanguard domains to Home Assistant webhook IDs
    # e.g., http://homeassistant.local:8123/api/webhook/mastermind_scholar
    webhook_id = f"mastermind_{domain.lower()}"
    
    payload = json.dumps({
        "domain": domain,
        "urgency": urgency,
        "active_task": title,
        "trigger_time": datetime.now().isoformat()
    }).encode("utf-8")

    url = f"{HA_URL}{webhook_id}"

    if dry_run:
        logger.info(f"🧪 [DRY RUN] Would fire webhook to {url}")
        logger.info(f"🧪 [DRY RUN] Payload: {payload.decode('utf-8')}")
        
        # Simulate the physical change logging
        if domain == "SCHOLAR":
            logger.info("-> Physical action: Dimming lights, switching to Cool White (Focus), blocking external IP traffic.")
        elif domain == "SOVEREIGN":
            logger.info("-> Physical action: Switching lights to Warm Amber, playing Lo-Fi focus stream.")
        elif domain == "TYCOON":
            logger.info("-> Physical action: Setting lights to Daylight, unblocking financial APIs.")
        elif urgency == "CRITICAL":
            logger.info("-> Physical action: Activating Red alert lighting for 5 seconds.")
            
        return True

    try:
        req = urllib.request.Request(url, data=payload, headers={'Content-Type': 'application/json'})
        with urllib.request.urlopen(req) as response:
            if response.status in [200, 201]:
                logger.info(f"✅ Successfully triggered Home Assistant scene for domain: {domain}")
                return True
    except urllib.error.URLError as e:
        # In a real setup, we might retry or just log. For this OS MVP, HomeAssistant might not be running locally.
        logger.warning(f"Failed to reach Home Assistant at {url}: {e.reason}")
        return False
    except Exception as e:
        logger.error(f"Unexpected error calling Home Assistant: {e}")
        return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mastermind OS <-> Home Assistant Bridge")
    parser.add_argument("--sync", action="store_true", help="Sync current environment to active task")
    parser.add_argument("--dry-run", action="store_true", help="Simulate the webhook without sending")
    args = parser.parse_args()

    if args.sync or args.dry_run:
        task = get_active_task()
        if task:
            logger.info(f"Currently active task: [{task['domain']}] {task['title']}")
            # We don't have explicit urgency in the routine JSON currently, so default to ROUTINE or infer
            trigger_ha_scene(
                domain=task["domain"], 
                urgency="ROUTINE", 
                title=task["title"],
                dry_run=args.dry_run
            )
        else:
            logger.info("No active Mastermind OS task scheduling currently. Maintaining default physical environment.")
