
import { CodeGenerationTask } from './types';

export class CodeMerger {
  merge(results: CodeGenerationTask[]): string {
    // Basic concatenation for Phase 7 MVP
    // Future: AST-based merging or git-patch generation
    
    let mergedOutput = "/* AUTO-GENERATED BY ANTIGRAVITY CORTEX */\n\n";

    results.forEach(task => {
      if (task.status === 'completed' && task.code) {
        mergedOutput += `\n// --- Task: ${task.id} (${task.assignedAgent}) ---\n`;
        mergedOutput += `// Files: ${task.files.join(', ')}\n`;
        mergedOutput += `// ----------------------------------------\n`;
        mergedOutput += task.code + "\n\n";
      } else if (task.status === 'failed') {
         mergedOutput += `\n// !!! FAILED TASK: ${task.id} !!!\n`;
         mergedOutput += `// Error: ${task.error}\n\n`;
      }
    });

    return mergedOutput;
  }
}
