name: Antigravity GitHub Sync
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  diagnostic-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Run Organization Health Check
        uses: antigravity-actions/org-audit@v1
        with:
          output-format: json
          
      - name: Post Results to Slack/Discord
        uses: antigravity-actions/notify@v1
        with:
          webhook-url: ${{ secrets.COMM_WEBHOOK }}
          message-template: 'org-health-summary'
          
      - name: Update GitHub Issues
        uses: antigravity-actions/github-sync@v1
        with:
          auto-create-issues: true
          tag-critical: true
