import os
import json
import requests
import logging
from datetime import datetime

# Configuration
HIPPOCAMPUS_URL = "http://localhost:8090" # Port mapping 8090:8000
OUTPUT_DIR = "/Users/infinite27/AILCC_PRIME/04_Intelligence_Vault/Hardship_Chronicles/Academic_Records/APPEAL_SUBMISSION_READY"
TEMPLATE_PATH = "/Users/infinite27/AILCC_PRIME/04_Intelligence_Vault/Hardship_Chronicles/Academic_Records/EVIDENCE_BUNDLE_V2.md"

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def generate_bundle():
    logging.info("🛡️ Initiating 'Shield' Appeal Bundle Generation...")
    
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        logging.info(f"Created output directory: {OUTPUT_DIR}")

    # 1. Gather Context via RAG
    queries = [
        "Joel Palk-Ricard 2023 withdrawal failure evidence",
        "Student loan financial barriers MtA 2023",
        "Disability and Meighen Centre accommodations history"
    ]
    
    recalled_intel = []
    for q in queries:
        try:
            response = requests.post(f"{HIPPOCAMPUS_URL}/memory/query", json={"query": q, "n_results": 3})
            if response.status_code == 200:
                data = response.json()
                if data['status'] == 'success':
                    for res in data['results']:
                        recalled_intel.append(f"- {res['content']} (Score: {1 - res['distance'] if res['distance'] is not None else 'N/A'})")
        except Exception as e:
            logging.warning(f"RAG Query failed for '{q}': {str(e)}")

    # 2. Construct the Bundle
    timestamp = datetime.now().strftime("%Y-%m-%d")
    bundle_id = f"bundle_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    
    manifest_content = f"""# 🛡️ APPEAL EVIDENCE BUNDLE [{bundle_id}]
**Generated**: {timestamp}  
**Subject**: Joel Palk-Ricard (ID: 026004)  
**Status**: SUBMISSION READY  

---

## 📅 RAG-RECALLED CONTEXTUAL EVIDENCE
This section contains fragments of intelligence reconstructed from the AILCC Neural Vault:

{chr(10).join(recalled_intel) if recalled_intel else "No supplemental context found in RAG."}

---

## 🏛️ CORE EVIDENCE BLOCKS (VERIFIED)

### 1. The Administrative Procedural Failure (Oct 2023)
Evidence of a good-faith attempt to vacate courses that was procedurally blocked by a financial hold, creating an inescapable academic penalty.

### 2. The 95% Completion Milestone
114 of 120 credits completed (95%). This demonstrates academic persistence and readiness for degree conferral upon administrative correction.

### 3. Disability Policy Conflict
Documentation of systematic friction between standard registrar withdrawal procedures and disability-managed course loads.

---

**Generated by AILCC Scholar Convergence Protocol v4.0**
*Source: Antigravity Neural Vault & Hippocampus RAG Service*
"""

    output_path = os.path.join(OUTPUT_DIR, f"Joel_Palk-Ricard_Appeal_Bundle_{datetime.now().strftime('%Y%m%d')}.md")
    with open(output_path, 'w') as f:
        f.write(manifest_content)
        
    logging.info(f"✅ Appeal bundle generated at: {output_path}")

if __name__ == "__main__":
    generate_bundle()
