import os
import time
import requests
from datetime import datetime, timedelta, timezone
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s [VISIONARY-BRIEF] %(message)s")

# Load Linear API Key from the dashboard .env.local
ENV_PATH = "/Users/infinite27/AILCC_PRIME/01_Areas/Codebases/ailcc/dashboard/.env.local"
LINEAR_API_KEY = None

try:
    with open(ENV_PATH, 'r') as f:
        for line in f:
            if line.startswith("LINEAR_API_KEY="):
                LINEAR_API_KEY = line.split("=", 1)[1].strip()
except Exception as e:
    logging.error(f"Failed to read Linear API Key: {e}")

if not LINEAR_API_KEY:
    logging.error("No Linear API Key found. Aborting Visionary Brief.")
    exit(1)

VAULT_DIR = "/Users/infinite27/AILCC_PRIME/04_Intelligence_Vault/Visionary_Briefs"
os.makedirs(VAULT_DIR, exist_ok=True)

GRAPHQL_URL = "https://api.linear.app/graphql"
# Look back exactly 24 hours
yesterday_iso = (datetime.now(timezone.utc) - timedelta(days=1)).isoformat().replace("+00:00", "Z")

QUERY = """
query GetClosedIssues($updatedAt: DateTimeOrDuration!) {
  issues(filter: { state: { name: { eq: "Done" } }, updatedAt: { gte: $updatedAt } }) {
    nodes {
      id
      title
      description
      completedAt
      estimate
    }
  }
}
"""

def generate_brief():
    logging.info("Querying Linear API for recently closed tickets...")
    headers = {
        "Authorization": LINEAR_API_KEY,
        "Content-Type": "application/json"
    }
    
    payload = {
        "query": QUERY,
        "variables": { "updatedAt": yesterday_iso }
    }
    
    res = requests.post(GRAPHQL_URL, json=payload, headers=headers)
    if res.status_code != 200:
        logging.error(f"Linear API error: {res.text}")
        return False
        
    data = res.json()
    issues = data.get("data", {}).get("issues", {}).get("nodes", [])
    
    date_str = datetime.now().strftime("%Y-%m-%d")
    brief_path = os.path.join(VAULT_DIR, f"{date_str}_Visionary_Brief.md")
    
    with open(brief_path, "w", encoding="utf-8") as f:
        f.write(f"# 🕊️ Visionary Brief: {date_str}\n\n")
        f.write("*Autonomous Swarm Intelligence Synopsis*\n\n")
        f.write("---\n\n")
        
        if not issues:
            f.write("No major tickets were closed in the last 24 hours. The swarm is calibrating or resting.\n")
        else:
            f.write(f"### The Swarm successfully closed {len(issues)} strategic objectives:\n\n")
            for issue in issues:
                f.write(f"- **[{issue['id']}] {issue['title']}**\n")
                if issue.get('description'):
                    # Truncate description down to 100 chars
                    desc = issue['description'].replace('\n', ' ')
                    if len(desc) > 100: desc = desc[:100] + "..."
                    f.write(f"  > {desc}\n")
                f.write("\n")
                
        f.write("\n---\n*Generated by the Mastermind Visionary Protocol.*")
        
    logging.info(f"✅ Visionary Brief successfully generated: {brief_path}")
    return True

if __name__ == "__main__":
    generate_brief()
