import type { NextApiRequest, NextApiResponse } from 'next';
import * as fs from 'fs';
import * as path from 'path';

/**
 * 🌌 AILCC Self-Modifying Architecture (Domain 10 — The Singularity Protocol)
 *
 * POST /api/singularity/scaffold-page
 *
 * The system proposes and generates new Next.js pages autonomously.
 * Given a page name and description, it:
 *   1. Scaffolds a production-ready Next.js page file
 *   2. Uses the local LLM (Ollama) to draft the page's core component
 *   3. Writes the file to the pages directory
 *   4. Logs the creation to the tamper-evident audit trail
 */

const DASHBOARD_DIR = '/Users/infinite27/AILCC_PRIME/01_Areas/Codebases/ailcc/dashboard';

const PAGE_TEMPLATE = (name: string, title: string, description: string, llmContent: string) => `import Head from 'next/head';
import { motion } from 'framer-motion';

/**
 * 🌌 ${title}
 * ${description}
 *
 * AUTO-GENERATED by AILCC Singularity Protocol
 * Generated: ${new Date().toISOString()}
 */

export default function ${name}Page() {
  return (
    <>
      <Head>
        <title>${title} | AILCC</title>
        <meta name="description" content="${description}" />
      </Head>
      <main className="min-h-screen bg-slate-950 text-white p-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-6xl mx-auto"
        >
          <div className="mb-8 border-b border-slate-800 pb-6">
            <h1 className="text-4xl font-bold font-mono text-white mb-2">${title}</h1>
            <p className="text-slate-400 font-mono">${description}</p>
            <div className="mt-3 text-[11px] font-mono text-slate-600 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-violet-500 animate-pulse inline-block" />
              AUTO-GENERATED BY AILCC SINGULARITY PROTOCOL
            </div>
          </div>

${llmContent}

        </motion.div>
      </main>
    </>
  );
}
`;

async function generatePageContentWithLLM(name: string, description: string): Promise<string> {
    try {
        const resp = await fetch('http://localhost:11434/api/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                model: 'llama3:latest',
                prompt: `You are a senior Next.js + TypeScript developer building the AILCC AI command system. Generate ONLY the inner JSX content (no imports, no export, no wrapper) for a dashboard page called "${name}" with description: "${description}". Use Tailwind-like inline className with slate/violet color palette. Return only JSX, no explanation.`,
                stream: false
            }),
            signal: AbortSignal.timeout(30000)
        });
        if (!resp.ok) throw new Error('Ollama unavailable');
        const data = await resp.json();
        const raw = (data.response as string ?? '').trim();
        // Indent all lines for proper JSX nesting
        return raw.split('\n').map(l => '          ' + l).join('\n');
    } catch {
        // Graceful fallback
        return `          <div className="p-8 bg-slate-900/60 border border-violet-500/20 rounded-2xl text-center">
            <p className="text-slate-400 font-mono text-sm">
              🌌 This page was autonomously scaffolded by the AILCC Singularity Protocol.
            </p>
            <p className="text-slate-600 font-mono text-xs mt-2">Connect Ollama to generate dynamic content.</p>
          </div>`;
    }
}

async function appendToAuditLog(action: string, details: string) {
    try {
        await fetch('http://localhost:3000/api/system/audit-log', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ action, source: 'SINGULARITY', details, agentId: 'AGT-CORTEX-SINGULARITY' })
        });
    } catch { /* non-critical */ }
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

    const { pageName, title, description } = req.body as {
        pageName: string; title: string; description?: string;
    };

    if (!pageName || !title) {
        return res.status(400).json({ error: 'pageName and title required' });
    }

    // Sanitize page name — lowercase, alphanumeric and hyphens only
    const safeName = pageName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const componentName = safeName.split('-').map((p: string) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
    const targetPath = path.join(DASHBOARD_DIR, 'pages', `${safeName}.tsx`);

    if (fs.existsSync(targetPath)) {
        return res.status(409).json({ error: `Page "${safeName}" already exists at ${targetPath}` });
    }

    const desc = description ?? `AILCC auto-generated page: ${title}`;

    // Generate LLM content
    const llmContent = await generatePageContentWithLLM(componentName, desc);
    const pageContent = PAGE_TEMPLATE(componentName, title, desc, llmContent);

    // Write the file
    fs.writeFileSync(targetPath, pageContent, 'utf-8');

    // Audit trail
    await appendToAuditLog('PAGE_SCAFFOLDED', `Created /${safeName} — "${title}". ${pageContent.length} chars written.`);

    return res.status(200).json({
        success: true,
        page: `/${safeName}`,
        file: targetPath,
        title,
        chars: pageContent.length,
        message: `Page "${title}" scaffolded autonomously. Run \`npm run dev\` to see it live.`
    });
}
