import os
import subprocess
import datetime
import logging

# Configure Logging
log_file = "06_System/Logs/changelog_gen.log"
os.makedirs(os.path.dirname(log_file), exist_ok=True)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
logger = logging.getLogger("ChangelogGen")

CHANGELOG_PATH = "CHANGELOG.md"

def generate_changelog():
    logger.info("✍️ Generating System Changelog...")
    
    # Get last 10 commits
    try:
        cmd = ["git", "log", "-n", "10", "--pretty=format:%h - %s (%cr) <%an>"]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        commits = result.stdout.strip()
    except subprocess.CalledProcessError:
        commits = "Unable to fetch git history."

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""# 📝 AILCC SYSTEM CHANGELOG

**Last Generated**: {timestamp}
**Target Environment**: AILCC-PRIME

## 🚀 Recent Updates

{commits}

## 🏛️ Strategic Progress (Phase 2)
- [x] Task 36: Comet Handshake (Data Extraction Vault)
- [x] Task 39: Valentine Design Overhaul (Telemetry)
- [x] Task 41: Batch Scholar Launch (Deep Focus)
- [x] Task 45: Airtable Strategic Hub Sync
- [x] Task 50: Linear Autonomous Issue Delegation

---
*Generated by Claude (The Architect)*
"""

    with open(CHANGELOG_PATH, 'w') as f:
        f.write(content)
        
    logger.info(f"✅ Changelog updated: {CHANGELOG_PATH}")

if __name__ == "__main__":
    generate_changelog()
