import os
import json
from datetime import datetime

# Simple markdown to text/minimal document generator
# In a real environment, this might use fpdf or python-docx
# For this implementation, we focus on structured Markdown reports that can be easily converted.

ROOT = "/Users/infinite27/AILCC_PRIME"
OUTBOX = f"{ROOT}/06_System/AILCC/outbox"
LOGS = f"{ROOT}/06_System/Logs"

def generate_report(title, content, agent_name="System"):
    """
    Generates a structured markdown report in the AILCC Outbox.
    """
    if not os.path.exists(OUTBOX):
        os.makedirs(OUTBOX)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"REPORT_{agent_name.upper()}_{timestamp}.md"
    filepath = os.path.join(OUTBOX, filename)

    report_content = f"""# {title}
**Generated by**: {agent_name}
**Timestamp**: {datetime.now().isoformat()}

---

{content}

---
*AILCC Mode 5: Autonomous Abundance*
"""

    with open(filepath, "w") as f:
        f.write(report_content)

    print(f"✅ Report generated: {filepath}")
    log_event(f"Report generated: {filename} by {agent_name}")
    return filepath

def log_event(message):
    with open(os.path.join(LOGS, "report_gen.log"), "a") as f:
        f.write(f"[{datetime.now().isoformat()}] {message}\n")

if __name__ == "__main__":
    # Test generation
    generate_report(
        "Mode 5 System Integrity Audit",
        "AILCC Mode 5 is fully operational. All core daemons (Web, Nexus, Sync) are responding correctly. Phase 6 Delegation is in progress via Linear MCP.",
        "Antigravity"
    )
